### ISSUE TITLE
Dont Compile on RaspiZero - Help

### ISSUE THREAD

**Issue by ludwich66** [twartzek/bme680-raspberry#2]
Hi,
i need help, i have this output errors .

i had checked before:
i2cdetect -y 1 --> It users the 0x77
gcc (Raspbian 4.9.2-10) 4.9.2

i don't understand the following output:
` pi@raspberrypizero:~/BOSCH` $ sudo gcc bme680_main.c bme680.c -o bme680
bme680_main.c: In function ‘user_i2c_write’:
bme680_main.c:102:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i=1; i<len+1; i++)
     ^
bme680_main.c:102:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile `

do you have any hints?

ludwich

**Comment by heinemml** [comment]
Hi,

the error already states the solution. Compile it like this:

```
gcc bme680_main.c bme680.c -o bme680 -std=c11
```

**Comment by ludwich66** [comment]
Thanks for this answer.
I could not start with the options.
C99 or C11 ?? C11 ran smoothly.

**Comment by heinemml** [comment]
Both would work.
The only issue is that in "the old" C Standard (aka pre-C99 (99/11 refers to the release year)) the variable needs to be defined before the loop like this:
```
int i;
for (i=1; i<len+1; i++)
```
